/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feluletek;

import alapOsztalyok.Jatekos;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import modellcsomag.RendezhetoListModel;

/**
 *
 * @author nbx
 */
public class InduloPanel extends javax.swing.JPanel {

    private Image hatterKep = new ImageIcon(this.getClass().getResource("/kepek/induloHatter.jpg")).getImage();
    private RendezhetoListModel<Jatekos> jatekosok = new RendezhetoListModel<>();
    
    /**
     * Creates new form InduloPanel
     */
    public InduloPanel() {
        initComponents();
    }

    /**
     *Kirajzol egy képet.
     * @param g
     */
    @Override
    protected void paintComponent(Graphics g) {
        g.drawImage(hatterKep, 0, 0, this.getWidth(), this.getHeight(), this);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJatek = new javax.swing.JButton();
        btnRanglista = new javax.swing.JButton();
        btnSugo = new javax.swing.JButton();

        btnJatek.setText("Játék");
        btnJatek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJatekActionPerformed(evt);
            }
        });

        btnRanglista.setText("Ranglista");
        btnRanglista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRanglistaActionPerformed(evt);
            }
        });

        btnSugo.setText("Súgó");
        btnSugo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSugoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSugo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRanglista, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJatek, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnJatek)
                .addGap(40, 40, 40)
                .addComponent(btnRanglista)
                .addGap(38, 38, 38)
                .addComponent(btnSugo)
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     *Eltüntei ezt a framet, majd megjelenít egy másikat.
     */
    private void btnJatekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJatekActionPerformed
        FoFrame foFrame = new FoFrame();
        foFrame.setVisible(true);
        JFrame frame = (JFrame) SwingUtilities.getRoot(this);
        frame.setVisible(false);
    }//GEN-LAST:event_btnJatekActionPerformed

    /**
     *Eltüntei ezt a framet, majd megjelenít egy másikat.
     */
    private void btnSugoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSugoActionPerformed
        SugoFrame sugoFrame = new SugoFrame();
        sugoFrame.setVisible(true);
        JFrame frame = (JFrame) SwingUtilities.getRoot(this);
        frame.setVisible(false);
    }//GEN-LAST:event_btnSugoActionPerformed

    /**
     *Eltüntei ezt a framet, majd megjelenít egy másikat.
     */
    private void btnRanglistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRanglistaActionPerformed
        RanglistaFrame ranglistaFrame = new RanglistaFrame();
        ranglistaFrame.setVisible(true);
        JFrame frame = (JFrame) SwingUtilities.getRoot(this);
        frame.setVisible(false);
    }//GEN-LAST:event_btnRanglistaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJatek;
    private javax.swing.JButton btnRanglista;
    private javax.swing.JButton btnSugo;
    // End of variables declaration//GEN-END:variables
}
