/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feluletek;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import vezerles.SzalVezerlo;

/**
 *
 * @author nbx
 */
public class JatekosPanel extends javax.swing.JPanel {

    private SzalVezerlo szalVezerlo;
    
    /**
     * Creates new form JatekosPanel
     */
    public JatekosPanel() {
        initComponents();
    }
    
    /**
     *
     * @param szalVezerlo
     */
    public void setSzalVezerlo(SzalVezerlo szalVezerlo) {
        this.szalVezerlo = szalVezerlo;
    } 
    
    /**
     *Megmondja, hogy a checkbox ki van-e pipálva.
     * @return
     */
    public boolean isNehez() {
        return checkNehez.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtJatekos = new javax.swing.JTextField();
        checkNehez = new javax.swing.JCheckBox();
        btnIndit = new javax.swing.JButton();
        btnFomenu = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setText("Játékos:");

        checkNehez.setBackground(new java.awt.Color(153, 153, 255));
        checkNehez.setText("Nehéz");

        btnIndit.setText("Indít");
        btnIndit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInditActionPerformed(evt);
            }
        });

        btnFomenu.setText("Főmenü");
        btnFomenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFomenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtJatekos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(12, 12, 12))
                            .addComponent(btnIndit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFomenu, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 60, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(checkNehez)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(txtJatekos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149)
                .addComponent(checkNehez)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(btnIndit)
                .addGap(60, 60, 60)
                .addComponent(btnFomenu)
                .addGap(98, 98, 98))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     *Elindítja a szálvezérlőt.
     */
    private void btnInditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInditActionPerformed
        szalVezerlo.indit();
    }//GEN-LAST:event_btnInditActionPerformed

    /**
     *Eltüntei ezt a framet, majd megjelenít egy másikat.
     */
    private void btnFomenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFomenuActionPerformed
        szalVezerlo.fomenubeLep();
        InduloFrame induloFrame = new InduloFrame();
        induloFrame.setVisible(true);
        JFrame frame = (JFrame) SwingUtilities.getRoot(this);
        frame.setVisible(false);
    }//GEN-LAST:event_btnFomenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFomenu;
    private javax.swing.JButton btnIndit;
    private javax.swing.JCheckBox checkNehez;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtJatekos;
    // End of variables declaration//GEN-END:variables
    
    /**
     *
     * @return
     */
    public String getNev() {
        return txtJatekos.getText();
    }
    
    /**
     *Letiltja az "Indít" gombot.
     */
    public void gombotAllit(){
        btnIndit.setEnabled(false);
    }
}
