/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feluletek;

import vezerles.SzalVezerlo;

/**
 *
 * @author nbx
 */
public class KijelzoPanel extends javax.swing.JPanel {

    private SzalVezerlo szalVezerlo;
    
    /**
     * Creates new form KijelzoPanel
     */
    public KijelzoPanel() {
        initComponents();
    }

    /**
     *
     * @param szalVezerlo
     */
    public void setSzalVezerlo(SzalVezerlo szalVezerlo) {
        this.szalVezerlo = szalVezerlo;
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPontszam = new javax.swing.JLabel();
        lblIdo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));

        lblPontszam.setText("Pontszám:");

        lblIdo.setText("Idő:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblPontszam)
                .addGap(292, 292, 292)
                .addComponent(lblIdo)
                .addContainerGap(708, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPontszam, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(lblIdo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblIdo;
    private javax.swing.JLabel lblPontszam;
    // End of variables declaration//GEN-END:variables

    /**
     *Kiírja az aktuális időt.
     * @param aktIdo
     */
    public void idoKiir(long aktIdo) {
        lblIdo.setText("Idő: " + aktIdo + " sec");
    }
    
    /**
     *Kiírja az aktuális pontszámot.
     * @param pontSzam
     */
    public void pontotKiir(int pontSzam) {
        lblPontszam.setText("Potszám: " + pontSzam);
    }
}
