/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feluletek;

import adatKezeles.AdatBevitel;
import adatKezeles.FajlKezeles;
import alapOsztalyok.Jatekos;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import modellcsomag.RendezhetoListModel;
import vezerles.SzalVezerlo;

/**
 *
 * @author nbx
 */
public class RanglistaPanel extends javax.swing.JPanel {

    private RendezhetoListModel<Jatekos> jatekosok = new RendezhetoListModel<>();
    /**
     * Creates new form RanglistaPanel
     */
    public RanglistaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFomenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstRanglista = new javax.swing.JList();

        setBackground(new java.awt.Color(153, 153, 255));
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btnFomenu.setText("Főmenü");
        btnFomenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFomenuActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstRanglista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnFomenu)))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFomenu)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     *Eltüntei ezt a framet, majd megjelenít egy másikat.
     */
    private void btnFomenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFomenuActionPerformed
        InduloFrame induloFrame = new InduloFrame();
        induloFrame.setVisible(true);
        JFrame frame = (JFrame) SwingUtilities.getRoot(this);
        frame.setVisible(false);
    }//GEN-LAST:event_btnFomenuActionPerformed

    /**
     *Beállítja a listaelem modelljét.
     */
    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        beallit();
        lstRanglista.setModel(jatekosok);
    }//GEN-LAST:event_formAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFomenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstRanglista;
    // End of variables declaration//GEN-END:variables
    
    /**
     *Beolvassa a modellt.
     */
    private void beallit() {
        try {
            AdatBevitel adatBevitel = new FajlKezeles();
            jatekosok = adatBevitel.jatekosModelBevitel();
        } catch (Exception e) {
            Logger.getLogger(SzalVezerlo.class.getName()).log(Level.SEVERE, null, e);
        }
    }
}
