/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feluletek;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author nbx
 */
public class SugoPanel extends javax.swing.JPanel {

    String sugoSzoveg = "A jaték célja, hogy a rendelkezésre álló idő alatt\nminnél több sárkányra kattintsunk.\n"
            + "Nehéz szinten lehetőség van bekerülni a ranglista első 5\nhelyezettje közé, amennyiben elegendő pontot érünk el,\n"
            + "de ebben az esetben gyorsabban mozognak a sárkányok\nés repülők is megfognak jelenni, amikre rákattintva\na játék véget ér.";
    
    /**
     * Creates new form SugoPanel
     * Beállítja a text area szöveg értékét.
     */
    public SugoPanel() {
        initComponents();
        txtAreaSugo.setText(sugoSzoveg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFomenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaSugo = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(153, 153, 255));

        btnFomenu.setText("Főmenü");
        btnFomenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFomenuActionPerformed(evt);
            }
        });

        txtAreaSugo.setEditable(false);
        txtAreaSugo.setColumns(20);
        txtAreaSugo.setRows(5);
        jScrollPane1.setViewportView(txtAreaSugo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(btnFomenu)
                .addContainerGap(168, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFomenu)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFomenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFomenuActionPerformed
        InduloFrame induloFrame = new InduloFrame();
        induloFrame.setVisible(true);
        JFrame frame = (JFrame) SwingUtilities.getRoot(this);
        frame.setVisible(false);
    }//GEN-LAST:event_btnFomenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFomenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaSugo;
    // End of variables declaration//GEN-END:variables
}
